config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root 'users#index'

  resources :users, only: %i[index show] do
    resources :posts, only: %i[create destroy index new show] do
      resources :comments, only: %i[create destroy new]
      resources :likes, only: %i[create]
    end
  end
end

app/models/comment.rb
# Comment class
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, class_name: 'Post'

  # adding "counter_cache: true" to the previous line automatically
  # increments the counter, and no longer is necessary the update_comments_count method
  after_save :increment_comments_count
  after_destroy :decrement_comments_count

  private

  def increment_comments_count
    post.increment!(:comments_count)
  end

  def decrement_comments_count
    post.decrement!(:comments_count)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  include ApplicationHelper

  def create
    author_id = @comment.author_id
    post_id = @comment.post_id

    if @comment.save
      flash[:notice] = 'Comment saved successfully'
      redirect_to user_post_path(author_id, post_id)
    else
      flash[:error] = 'Comment not saved'
      redirect_to new_user_post_comment_path(author_id, post_id)
    end
  end

  def destroy
    @comment.destroy
    redirect_to request.referer
  end

  def new
    # automated
  end

  protected

  def comment_params
    params.require(:comment).permit(:text).merge(params.slice(:post_id).permit(:post_id))
  end
end

app/views/comments/_comment.html.erb
<div class="row comment">
  <span>
    <%= comment.author.name %>:
    <%= comment.text %>
  </span>
  <% if can? :destroy, comment %>
    <%= button_to "Delete", user_post_comment_path(comment.author_id, comment.post_id, comment.id), data: { confirm: "Are you sure?" }, method: :delete, class: "delete-comment" %>
  <% end %>
</div>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<% flash.each do |key, message| %>
  <div class="error-message"><%= message %></div>
<% end %>

<%= form_with model: @comment, url: user_post_comments_path do |form| %>
  <div>
    <%= form.label :text, "Comment" %><br>
    <%= form.text_area :text %>
  </div>
  <%= form.submit %>
<% end %> 