config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root 'users#index'

  resources :users, only: %i[index show] do
    resources :posts, only: %i[create destroy index new show] do
      resources :comments, only: %i[create destroy new]
      resources :likes, only: %i[create]
    end
  end
end

app/models/post.rb
# Post class
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :likes, foreign_key: 'post_id', dependent: :delete_all
  has_many :comments, foreign_key: 'post_id', dependent: :delete_all

  # adding "counter_cache: true" to the previous line automatically increments
  # the counter, and no longer is necessary the update_posts_count method
  after_save :increment_posts_count
  after_destroy :decrement_posts_count

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_count, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_count, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def all_comments
    comments.includes([:author]).order(created_at: :desc)
  end

  def recent_comments
    all_comments.limit(5)
  end

  def fulltext(short: false)
    short ? "#{text[0..150]}..." : text
  end

  private

  def increment_posts_count
    author.increment!(:posts_count)
  end

  def decrement_posts_count
    author.decrement!(:posts_count)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  include ApplicationHelper

  def create
    if @post.save
      flash[:notice] = 'Post saved successfully'
      redirect_to user_path(@post.author_id)
    else
      flash[:error] = 'Post not saved'
      redirect_to new_user_post_path(@post.author_id)
    end
  end

  def destroy
    @post.destroy

    if current_page?(user_post_path(@post.author_id, @post.id))
      redirect_to user_posts_path(@post.author_id)
    else
      redirect_to request.referer
    end
  end

  def index
    author_id = params[:user_id]
    @posts = @posts.includes([:author]).rewhere(author_id:)
    @user = @posts.length.zero? ? User.find(author_id) : @posts.first.author
  end

  def new
    # automated
  end

  def show
    # automated
    #   @post = Post.find(params[:id])
    # rescue ActiveRecord::RecordNotFound
    #   redirect_to action: 'index'
  end

  protected

  def post_params
    # params.require(:post).permit(:title, :text).merge({ author_id: params[:user_id] }.permit(:author_id))
    params.require(:post).permit(:author_id, :title, :text)
  end
end

app/helpers/post_helper.rb
module PostHelper
  def with_comments?(post)
    post.comments_count.positive? && !current_page?(user_path(post.author_id))
  end

  def short_text?(post)
    !current_page?(user_post_path(post.author_id, post.id))
  end
end

app/views/posts/_comments.html.erb
<% if with_comments?(post) %>
  <div id="comment-list" class="column box">
    <% if short_text?(post) %>
      <%= render post.recent_comments %>
    <% else %>
      <%= render post.all_comments %>
    <% end %>
  </div>
<% end %>

app/views/posts/_count.html.erb
Comments: <%= post.comments_count %>, Likes: <%= post.likes_count %>

app/views/posts/_footer.html.erb
<% if short_text?(post) %>
  <div class="row-right">
    <h4><%= render 'posts/count', post: post %></h4>
  </div>
<% end %>
<div class="row-right">
  <%= button_to 'New comment', new_user_post_comment_path(post.author_id, post.id), method: :get %>
  <% if can? :create, Like && !current_user?(post.author_id) %>
    &nbsp;
    <%= button_to 'Like', user_post_likes_path(post.author_id, post), method: :post %>
  <% end %>
</div>

app/views/posts/_header.html.erb
<% if short_text?(post) %>
  <h3><%= link_to(user_post_path(post.author_id, post.id)) { post.title } %></h3>
<% else %>
  <div class="row-justify">
    <h3><%= post.title %> by <%= link_to(user_path(post.author_id)) { post.author.name } %> </h3>
    <h4><%= render 'posts/count', post: post %></h4>
  </div>
<% end %>
<% if can? :destroy, post %>
  <%= button_to "Delete", user_post_path(post.author_id, post.id), data: { confirm: "Are you sure?" }, method: :delete, class: "delete-post" %>
<% end %>

app/views/posts/_post.html.erb
<div class="post">
  <div class="column box">
    <%= render 'posts/header', post: post %>
    <p><%= post.fulltext(short: short_text?(post)) %></p>
    <%= render 'posts/footer', post: post %>
  </div>
  <%= render 'posts/comments', post: post %>
</div>

app/views/posts/index.html.erb
<input type="hidden" value="<%= "Here is a list of all Posts by User with id: #{@user.id}" %>" />
<%= render @user %>
<div id="post-list">
  <%= render @posts %>
</div>
<div class="row-center"><h3>Pagination</h3></div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<% flash.each do |key, message| %>
  <div><%= message %></div>
<% end %>

<%= form_with model: @post, url: user_posts_path do |form| %>
  <div>
    <%= form.label :title, "Title" %><br>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :text, "Text" %><br>
    <%= form.text_area :text %>
  </div>
  <%= form.submit %>
<% end %> 

app/views/posts/show.html.erb
<input type="hidden" value="<%= "Here is the specific Post with id: #{@post.id} by User with id: #{@post.author_id}" %>" />
<div class="box-no-border">
  <%= render @post %>
</div>